import "./globals.css";

export const metadata = {
  title: "미미콘 테스트",
  description: "Generated by Conan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-screen-md m-auto">{children}</body>
    </html>
  );
}
